<?php
/**
 * Jjcommerce_TrustpilotIntegration
 *
 * PHP version 5.x
 *
 * @category  PHP
 * @package   Jjcommerce\TrustpilotIntegration
 * @author    Sumit Verma <sumit@2jcommerce.in>
 * @copyright 2017 Copyright 2J Commerce, Inc. http://www.2jcommerce.in/
 * @license   http://www.2jcommerce.in/ Private
 * @link      http://www.mickgeorge.com/
 */
?>
<script type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.sync.bootstrap.min.js" async></script>

